[package]
name = "SunShare"
version = "1.0.0"
authors = []

[addresses]
SunShare = '0x9063b0cae7dd97c0491259a99ef90b35a93d26248c3a4c295872b158cbfdcac7'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
